# Generated by Django 4.1.7 on 2023-04-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_invalid username'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminotp',
            name='otp_for',
            field=models.CharField(choices=[('0', 'Password Reset OTP'), ('1', 'Profile Email Change OTP'), ('2', 'Email Verify OTP')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
