# Generated by Django 4.1.7 on 2023-04-28 10:41

import accounts.file_save
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminotp_otp_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('full_name', models.CharField(default=None, max_length=75)),
                ('member_photo', models.ImageField(upload_to=accounts.file_save.member_personal_image)),
                ('aadhar_image', models.ImageField(upload_to=accounts.file_save.member_aadhar_image)),
                ('firm_name', models.CharField(default=None, max_length=100)),
                ('firm_contact_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('firm_address', models.TextField()),
                ('firm_vat_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('firm_vat_image', models.ImageField(default=None, upload_to=accounts.file_save.firm_vat_image)),
                ('firm_tin_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('firm_tin_image', models.ImageField(default=None, upload_to=accounts.file_save.firm_tin_image)),
                ('firm_pan_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('firm_pan_image', models.ImageField(default=None, upload_to=accounts.file_save.firm_pan_image)),
                ('gst_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('trade_license_image', models.ImageField(upload_to=accounts.file_save.trade_license_image)),
                ('visiting_card_image', models.ImageField(default=None, upload_to=accounts.file_save.visiting_card_image)),
                ('resolution_image', models.ImageField(default=None, upload_to=accounts.file_save.resolution_image)),
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_mobile', models.CharField(default=None, error_messages={'unique': 'Mobile Number already in use'}, max_length=10, unique=True)),
                ('member_email_verified', models.BooleanField(default=False)),
                ('member_mobile_verified', models.BooleanField(default=False)),
                ('aadhar_no', models.CharField(default=None, error_messages={'unique': 'Aadhar number already in use'}, max_length=12, unique=True)),
                ('firm_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.district')),
                ('user', models.OneToOneField(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('full_name', models.CharField(default=None, max_length=75)),
                ('member_photo', models.ImageField(upload_to=accounts.file_save.member_personal_image)),
                ('aadhar_no', models.CharField(default=None, max_length=12)),
                ('aadhar_image', models.ImageField(upload_to=accounts.file_save.member_aadhar_image)),
                ('member_mobile', models.CharField(max_length=10)),
                ('firm_name', models.CharField(default=None, max_length=100)),
                ('firm_contact_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('firm_address', models.TextField()),
                ('firm_vat_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('firm_vat_image', models.ImageField(default=None, upload_to=accounts.file_save.firm_vat_image)),
                ('firm_tin_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('firm_tin_image', models.ImageField(default=None, upload_to=accounts.file_save.firm_tin_image)),
                ('firm_pan_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('firm_pan_image', models.ImageField(default=None, upload_to=accounts.file_save.firm_pan_image)),
                ('gst_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('trade_license_image', models.ImageField(upload_to=accounts.file_save.trade_license_image)),
                ('visiting_card_image', models.ImageField(default=None, upload_to=accounts.file_save.visiting_card_image)),
                ('resolution_image', models.ImageField(default=None, upload_to=accounts.file_save.resolution_image)),
                ('id_membership_req', models.AutoField(primary_key=True, serialize=False)),
                ('membership_is_approved', models.BooleanField(default=False)),
                ('member_email', models.EmailField(max_length=254)),
                ('firm_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.district')),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
