# Generated by Django 4.1.7 on 2023-05-08 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_member_membershiprequest_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.PositiveIntegerField(error_messages={'unique': 'Membership Type with this duration already exists'}, unique=True)),
            ],
            options={
                'db_table': 'membership_type',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='membership_expiry_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_start_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.membershiptype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='membership_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.membershiptype'),
            preserve_default=False,
        ),
    ]
