# Generated by Django 4.1.7 on 2023-05-22 08:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_membershiptype_member_membership_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOTP',
            fields=[
                ('id_otp', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry', models.DateTimeField()),
                ('otp_for', models.CharField(choices=[('0', 'Password Reset OTP')], max_length=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_set', to='accounts.member')),
            ],
            options={
                'db_table': 'member_otp',
            },
        ),
    ]
