# Generated by Django 4.1.3 on 2023-06-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_memberotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='aadhar_no',
            field=models.CharField(default=None, error_messages={'unique': 'Aadhar number already in use'}, max_length=18, unique=True),
        ),
    ]
